version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: rajeshci
          environment:
            GOOGLE_INSTANCE_NAME: onnbazaar
            GOOGLE_SERVICE_NAME: 573964864377-compute@developer.gserviceaccount.com
            command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: |
          # gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account ${GOOGLE_SERVICE_NAME} --key-file ${HOME}/gcloud-service-key.json
          # gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud config set project ${GOOGLE_INSTANCE_NAME}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: ssh
          environment:
            SSH_KEY: circleci.rsa
            GCP_FOLDER: /var/www/html/demopipeline/
            GCP_PROJECT_INSTANCE: onnbazaar-instance
          command: |
            ssh-keygen -f ${SSH_KEY} -t rsa -N ''
            cat circleci.rsa.pub
            export GCP_FOLDER_PATH=${GCP_FOLDER}
            export SSH_RUN="gcloud compute ssh root@${GCP_PROJECT_INSTANCE} --ssh-key-file=${SSH_KEY}"
            ${SSH_RUN} --command="cd ${GCP_FOLDER_PATH} && git pull"

            